### ISSUE TITLE
Issue with the AuthorizatoinCodeContext

### ISSUE THREAD

**Issue by nedvice-sv** [microsoft/kiota-samples#6261] opened 2024-08-14 14:23 UTC
Not entirely sure if you guys are watching this repository or not. 1 issue - last mentioned nearly a year ago.

I'm currently following the steps on the MS Website itself (https://learn.microsoft.com/en-us/openapi/kiota/tutorials/php-azure?tabs=portal)

The AuthorizationCodeContext is working fine with the `authCode` for once. When I refresh the page its gone and I need to repeat the whole process again. I need this 'working' without further consent of the user after it gave consent once. But there is nothing that mentions anything about the other options or how to make this work permenantly.

I hope you'll see this and could reply to me!

Thanks in advance - Sanne

**Comment by baywet** [comment] 2024-08-14 17:02
Hi @nedvice-sv 
Thank you for using kiota and for reaching out.
You are correct, we're not actively monitoring this repo.
Can you please create an issue on this repository instead please?
https://github.com/microsoft/kiota-authentication-phpleague-php/

**Comment by Ndiritu** [comment] 2024-08-19 13:58
duplicate of https://github.com/microsoft/kiota-authentication-phpleague-php/issues/91

**Closed by Ndiritu** 2024-08-19 13:58 UTC
